### ISSUE TITLE
Heatpump in offline state give error

### ISSUE THREAD

**Issue by HenrikBurton** [klejejs/ha-thermia-heat-pump-integration#17]
I have two heatpumps in my Thermia genesis account where one of them are a ghost that i can not remove. The ghost heatpump is in offline state with **'isOnline': False**. My issue is that the entities of my actual heatpump are not updated except from the initial reading and in addition i get a error message in the CORE system log in HA for each poll cycle.

_2022-02-10 18:47:51 ERROR (MainThread) [ThermiaOnlineAPI.model.HeatPump] Error in getting device's temperature status. No temperature register index._

A sugested improvment is that the integration are able to flag to HA that the heatpump is offline.

**Comment by HenrikBurton** [comment]
Thanks, let me know if I can help some how.

**Comment by klejejs** [comment]
Version 2.7 should fix the issue. Please report if it is still present or any other issues arise.

**Comment by HenrikBurton** [comment]
Tested the fix with version 2.7 and API 2.12 but i still get the same message in the CORE logg:

_2022-02-13 12:17:07 ERROR (MainThread) [ThermiaOnlineAPI.model.HeatPump] Error in getting device's temperature status. No temperature register index._

I have tested to inactivate the second heatpump entity in Home Assistant with the same result.

**Comment by HenrikBurton** [comment]
HA shows no info about online/offline status and only values for the online units entities from the first poll.

I'm an bit familiar with programing and debuging as being in the IT-industy since begining of the 80'th. Lately it's has mostley been focus on project management but the passion is still alive. Learned Phyton last year ....

I will send You the JSON for the Info and Status requests for both my heatpumps on your gmail.

**Comment by klejejs** [comment]
Hello! Please check out release 2.8. It should fix the issue, but please report back.

**Note:** As mentioned in release notes, unfortunately, I had previously made a mistake in config flow, so after updating to the latest version, you will see empty duplicate devices of your heat pumps and the only way to remove them is by deleting the integration and adding it once again. I am sorry for the inconvenience. 😞

**Comment by HenrikBurton** [comment]
Hi! After removing the integration and reinstalling i still see the same messages in the CORE-log (every 10-15 sec a double log entry):

2022-02-15 09:07:44 ERROR (MainThread) [ThermiaOnlineAPI.model.HeatPump] Error in getting device's temperature status. No temperature register index.
2022-02-15 09:07:44 ERROR (MainThread) [ThermiaOnlineAPI.model.HeatPump] Error in getting device's temperature status. No temperature register index.
2022-02-15 09:07:57 ERROR (MainThread) [ThermiaOnlineAPI.model.HeatPump] Error in getting device's temperature status. No temperature register index.
2022-02-15 09:07:57 ERROR (MainThread) [ThermiaOnlineAPI.model.HeatPump] Error in getting device's temperature status. No temperature register index.

I'll be happy to help you just let me know.

Thanks!

**Comment by klejejs** [comment]
The latest release should remove temperature status fetching in case your device is not available. Please check it out and report back.

**Comment by HenrikBurton** [comment]
I get the same messages as before and also two of them in a burst at the same time.

**Comment by klejejs** [comment]
Hmm, I don't get this. I actually also have a heat pump offline right now, but I don't have the same issue.
Has this part in the logs changed? `(MainThread) [ThermiaOnlineAPI.model.HeatPump] `
Does it show device id there now?

**Comment by HenrikBurton** [comment]
It's the same message except that the heatpump ID as added:

_2022-02-18 09:01:31 ERROR (MainThread) [ThermiaOnlineAPI.model.HeatPump.1532771] Error in getting device's temperature status. No temperature register index.
2022-02-18 09:01:31 ERROR (MainThread) [ThermiaOnlineAPI.model.HeatPump.1532771] Error in getting device's temperature status. No temperature register index._

Strange thing is that 1532771 is my working heatpump, not the zombie/offline one.

**Comment by klejejs** [comment]
Thanks for the info. Yes, I had a feeling that we might be looking for a problem in the wrong place 😄 
I will recheck the device info status that you sent me and try to find a fix.
I'll let you know how it goes.

**Comment by klejejs** [comment]
The latest integration version should hide these errors, please check if they have disappeared.
